const bcrypt = require('bcryptjs');
const data = {
  users: [
    {
      name: 'Bing',
      email: 'admin@zk.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Jon',
      email: 'jon@zk.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Apple Air pods',
      category: 'Devices',
      image: '/images/Airpods.jpeg',
      price: 200,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Mackbook',
      category: 'Devices',
      image: '/images/Macbook.jpg',
      price: 900,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Air Pods Max',
      category: 'Apple',
      image: '/images/AirpodsMax.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Ipad',
      category: 'Pants',
      image: '/images/Ipad.jpeg',
      price: 78,
      countInStock: 15,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Samsung A7',
      category: 'Device',
      image: '/images/1.png',
      price: 605,
      countInStock: 5,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Samsung Smart Watch',
      category: 'Device',
      image: '/images/2.jpeg',
      price: 119,
      countInStock: 12,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Apple Smart Watch',
      category: 'Device',
      image: '/images/3.jpeg',
      price: 199,
      countInStock: 12,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};

module.exports = data;
